In [80]:
# We are going to use sklearn for the following Machine Learning Algorithms
# Bayes (NB)
# SVM 
# Regression (linear or poly)
# Random Forest
# 

In [81]:
import seaborn as sns
import pandas as pd
import numpy as np

# sklearn imports below
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.datasets import load_iris


In [82]:
def mlBayes(X, y, p):
  # init y_predict
  y_pred = -1

  nbObj = GaussianNB()   # create an instance of the object
  nbObj.fit(X,y)        # fit or train the model
  y_pred = nbObj.predict(p)

  return y_pred

def mlSVM(X, y, p):
  # init y_predict
  y_pred = -1
  
  # fit or train the model
  svcObj = SVC()
  svcObj.fit(X,y)
  y_pred = svcObj.predict(p)

  return y_pred

def mlRegression(X, y, p):
  # init y_predict
  y_pred = -1
  
  regObj = LinearRegression()
  regObj.fit(X, y)
  y_pred = regObj.predict(p)

  return y_pred

def mlRandomForest(X, y, p):
  # init y_predict
  y_pred = -1

  rfObj = RandomForestClassifier()
  rfObj.fit(X, y)
  y_pred = rfObj.predict(p)

  return y_pred


In [83]:
def main():
  Features = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
  Class = np.array([1, 1, 1, 2, 2, 2])
  Predict = [[-0.8, -1]]

  # download Iris Data 
  Features, Class = load_iris(return_X_y=True)
  Predict = [[-0.8, -1, 0, 0]]
  print(Features)
  print(Class)

  y_bayes = mlBayes(Features, Class, Predict)
  y_svm = mlSVM(Features, Class, Predict)
  y_reg = mlRegression(Features, Class, Predict)
  y_rf  = mlRandomForest(Features, Class, Predict)

  print('The predicted value is bayes = ', y_bayes)
  print('The predicted value is svm   = ', y_svm)
  print('The predicted value is reg   = ', y_reg)
  print('The predicted value is rfores= ', y_rf)

  return 

In [84]:
main()

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.